### ISSUE TITLE
Full Weekend of Refactorization :-)

### ISSUE THREAD

**Issue by UlisesGascon** [GoblinDBRocks/GoblinDB#18]
During a OSWeekends event :)

**Comment by CodingCarlos** [comment]
I've gone crazy and... well... Eh... [I've done a refactor branch](https://github.com/GoblinDBRocks/GoblinDB/tree/refactor). There was a lot of things to do before that but... I didn't like to work in a code we'll have to refactor.

 Actually, everything is working, but not all the code is fully refactored. I still need to work in:
- [ ] Ambush functions validations
- [ ] Silent mode #13 
- [ ] Prepare Error constants for better consistency (also will be great for #14)

Also, I think this is a good moment to define code linting and code documentation. I've not added any .eslintrc file to root (old one still in _old folder) because I want our code to be consistent.

I'll still working on this, and updating this issue's checklist when I go further in that features.

**Comment by CodingCarlos** [comment]
Fixed in #30 and #31
