### ISSUE TITLE
ECMAScript code version.

### ISSUE THREAD

**Issue by Sediug** [GoblinDBRocks/GoblinDB#35]
Some parts of the code is using ES6 (ES2015) features while the rest of them is using ES5. I think we should define what ECMAScript version do we want and stick to it.

**Comment by UlisesGascon** [comment]
ES6 (ES2015) is great for me. What do you think @CodingCarlos ?

**Comment by CodingCarlos** [comment]
**My official view:** ES6 has a lot of cool features, but a lot of crap _(as classes, arrow functions or templates)_. A good JS programmer, I think, shall know when to use one or other functionality, understanding the best option, and the consequences of using that code instead of other.

Sticking to a "version" sounds more "hipster" than intelligent since the "old" specification is not deprecated (just [some features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features), that we shall avoid using...), but the "newer" have added it more features.  

All this said I trust on your choices and decisions since I think you're great JS programmers. Do what you feel more comfortable to ;)


> My personal view: I'll never use features such as Classes _(syntactic sugar that don't follow the traditional OOP rules a Class shall follow)_, arrow functions _(wtf is happening with `this`? One of the most powerful js features to the thrash)_ or templates _(unclear, dirty and unnecessary shit)_. 
>
> Stick to things in such dynamic language as JS is like running with only one leg because a Paralympic athlete runs faster than you in that way.

**Comment by Sediug** [comment]
When we don't want / need to use "this" It's good for me to use arrow functions because you make your code more readable and easy for other people that doesn have to know what is **this** in that context xDD **This** is powerfull but could be also a pain in the ass in some cases haha. Anyway I was talking mostly about to use const and let instead of var, and thinks like that.

Then I'd say we use the best that suits our needs and go on! :+1:
